{ config, pkgs, inputs, ... }: {
  environment.systemPackages = with pkgs; [
    git
    kitty
    ghostty
    stow
    playerctl
    bibata-cursors
    libnotify
    nixd
    nixfmt
    qt6.qtdeclarative
    vscode
    adw-gtk3
    tumbler
    gdk-pixbuf
    ffmpeg
    ffmpegthumbnailer
    nautilus
    code-nautilus
    libpng
    libjpeg
    libheif
    libavif
    libjxl
    webp-pixbuf-loader
    inputs.hyprmod.packages.${pkgs.stdenv.hostPlatform.system}.default
    discord
  ];
}
